# Authentication configuration for LoginAbility

# Database configuration for Huawei Cloud MySQL
database:
  host: "e6ea2387617046a283e6b583b0fc9a31in01.internal.cn-south-1.mysql.rds.myhuaweicloud.com"
  # host: "localhost"
  user: "root"
  password: "!Y12345678"  # Replace with actual password
  db: "sales_management"  # Replace with your actual database name
  charset: "utf8mb4"

# Fallback configuration (used if database connection fails)
users:
  admin:
    password: "admin123"
    merchant_id: "merchant1"
  user1:
    password: "password123"
    merchant_id: "merchant1"
  user2:
    password: "password456"
    merchant_id: "merchant2"

# Fallback merchant information
merchants:
  merchant1:
    bg_url: "https://example.com/merchant1/background.jpg"
    bot_id: "bot_merchant1"
    user_id: "user_merchant1"
    coze_token: "coze_token_merchant1"
  merchant2:
    bg_url: "https://example.com/merchant2/background.jpg"
    bot_id: "bot_merchant2"
    user_id: "user_merchant2"
    coze_token: "coze_token_merchant2"