server:
  port: 8000
  host: "0.0.0.0"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"

metrics:
  enabled: true
  port: 9090

huaweicloud:
  obs:
    access_key_id: "HPUAZPZBF40NS0MKCXJD"
    secret_access_key: "Qm1VPOQhoLgIJYgOI4tAlmkuxrqwonNzdHYzoSOW"
    server: "obs.cn-south-1.myhuaweicloud.com"  # 根据实际区域修改
    bucket_name: "obs-270d"